// examples/svelte-star-stream/src/App.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { useStarStream } from '@star-stream/core';
  import Graph from './Graph.svelte';

  let stars: number[] = [];
  let mean: number;
  let stdDev: number;

  const { addStar, removeStar, reAlignStar } = useStarStream(100, [0, 100]);

  const updateStars = () => {
    stars = useStarStream(100, [0, 100]).stars;
    mean = useStarStream(100, [0, 100]).mean;
    stdDev = useStarStream(100, [0, 100]).stdDev;
  };

  onMount(() => {
    updateStars();
  });

  const handleAddStar = () => {
    addStar(Math.random() * 100);
    updateStars();
  };

  const handleRemoveStar = () => {
    removeStar(stars.length - 1);
    updateStars();
  };

  const handleReAlignStars = () => {
    reAlignStar([50, 75]);
    updateStars();
  };
</script>

<style>
  @import './app.css';
</style>

<main>
  <h1>Star Stream Example</h1>
  <Graph {stars} />
  <div>
    <button on:click={handleAddStar}>Add Star</button>
    <button on:click={handleRemoveStar}>Remove Star</button>
    <button on:click={handleReAlignStars}>Re-align Stars</button>
  </div>
  <div>
    <p>Mean: {mean}</p>
    <p>Standard Deviation: {stdDev}</p>
  </div>
</main>

// examples/react-star-stream/src/App.tsx
import React from 'react';
import './App.css';
import StarChart from './StarChart';
import { useStarStream } from '@star-stream/core';

function App() {
  const {
    stars,
    mean,
    stdDev,
    addStar,
    removeStar,
    reAlignStar,
  } = useStarStream(100, [0, 100]);

  return (
    <div className="App">
      <h1>Star Stream Example</h1>
      <StarChart stars={stars} />
      <div>
        <button onClick={() => addStar(Math.random() * 100)}>Add Star</button>
        <button onClick={() => removeStar(stars.length - 1)}>Remove Star</button>
        <button onClick={() => reAlignStar([50, 75])}>Re-align Stars</button>
      </div>
      <div>
        <p>Mean: {mean}</p>
        <p>Standard Deviation: {stdDev}</p>
      </div>
    </div>
  );
}

export default App;
